[metadata]
description_file = Readme.md
name = onecache
version = 0.3.1.post1
description = A lightweight and efficient caching library
long_description = file: Readme.md
long_description_content_type = text/markdown
author = Your Name
author_email = your@email.com
license = MIT

[aliases]
test = pytest

[tool:pytest]
python_files = **/*.py
testpaths = tests/
python_functions = test_*
addopts = --cov=onecache --cov-report term --cov-report html

[coverage:run]
relative_files = True

[bdist_wheel]
universal = 1

[egg_info]
tag_build =
tag_date = 0
