[metadata]
description_file = Readme.md
[aliases]
test=pytest
[tool:pytest]
python_files = **/*.py
testpaths = tests/
python_functions = test_*
addopts = --cov=onecache --cov-report term --cov-report html
[coverage:run]
relative_files = True
[bdist_wheel]
universal = 1
[egg_info]
tag_build =
tag_date = 0
